include:
  - board: nice_nano
    shield: sofle_left
    cmake-args: -Dboard_revision=2.0.0 -DSHIELD_LIST="nice_view_adapter;nice_view"
  - board: nice_nano
    shield: sofle_right
    cmake-args: -Dboard_revision=2.0.0 -DSHIELD_LIST="nice_view_adapter;nice_view"
